name: watersupply
channels:
  - conda-forge
dependencies:
  - catboost=1.2.2
  - cdsapi=0.6.1
  - esda=2.5.1
  - fiona=1.9.5
  - gdal=3.7.3
  - geopandas=0.14.1
  - giddy=2.3.4
  - imbalanced-learn=0.11.0
  - joblib=1.3.2
  - keras=2.13.1
  - libpysal=4.9.2
  - lightgbm=4.1.0
  - loguru=0.7
  - mapie=0.7.0
  - netCDF4=1.6.5
  - numba=0.58
  - numpy=1.26.2
  - odc-stac=0.3.8
  - pandas=2.1.3
  - pip=23.3
  - planetary-computer=1.0.0
  - pointpats=2.4.0
  - pydantic=1.10
  - pygrib=2.1.5
  - pykrige=1.7.1
  - pyproj=3.6.1
  - pystac=1.9.0
  - pystac-client=0.7.5
  - pytest=7.4
  - python=3.10.13
  - pytorch=1.13.1=cpu*
  - pytorch-lightning=2.1.1
  - rasterio=1.3.9
  - richdem=2.3.0
  - rioxarray=0.15.0
  - salem=0.3.9
  - spreg=1.4.2
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - shapely=2.0.2
  - statsmodels=0.14.0
  - tensorflow=2.13.1=cpu*
  - tqdm=4.66
  - xagg=0.3.1.1
  - xarray=2023.11.0
  - xgboost=1.7.6=cpu*
  - pip:
      - quantile-forest==1.2.3
  # R packages
  - r-base=4.3.2
  - r-plyr=1.8.9
  - r-terra=1.7
  - r-sf=1.0
  - r-zoo=1.8
  - r-doparallel=1.0.17
  - r-foreach=1.5.2
  - r-iterators=1.0.14
  - r-nlme=3.1
  - r-mgcv=1.9
  - r-qgam=1.3.4
  - r-modelr=0.1.11
  - r-missmda=1.19
  - r-mvtnorm=1.2
  - r-mice=3.16.0
  - r-factominer=2.9
  - r-matrix=1.6
  - r-rcpp=1.0.11
  - r-dataretrieval=2.7.14
  - r-dplyr=1.1.4
  - r-tidyr=1.3.0
  - r-lubridate=1.9.3
  - r-readr=2.1.4
  - r-stringr=1.5.1
